### PR TITLE
Update foo.go

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by geeknoid** [comment]
@rcaballeromx @frankbu @adammil2000 @nmittler Here's the new welcome message that'll be displayed to contributors to istio.io if they've never done a contribution, or if it is their first contribution in 90 days.

**Comment by frankbu** [comment]
Nice. The third bullet oddly seems to have a line break between "the" and "status section ...". Also should the forth bullet mention that to make a fix to the current doc, add the cherry-pick label?

**Comment by nmittler** [comment]
Looks great!

**Comment by rcaballeromx** [comment]
The text is awesome @geeknoid I just took an editorial pass to it. PTAL

😊 Welcome! Thank you for your contribution. This is either your first contribution to the Istio documentation repo, or it's been awhile since you've been here. 
We want to share following things you should know:

* Learn about how we write and maintain the Istio documentation, the style guidelines we adehre 
   to, and all the available web site features in our [Contributing to the Docs](https://istio.io/about/contribute) page.
* A few minutes after your PR is submitted, an automatic preview of your change is
   built. This is a fully functional copy of the istio.io website. To find this preview, click on
   the **Details** link next to the `deploy/netlify` entry in the Status section at the bottom of this
   page.
* We care about the quality of our content and we've put in place a number of checks to ensure 
   our documentation is top notch. We do spell checking, we sanitize the markdown, we ensure all 
   hyperlinks point to valid location, and more. If your PR doesn't pass one of these checks, you'll 
   see a red X in the status section of the page. Click the **Details** link to get a list of the 
   problems with your PR.
   Fix those problems and push an update to your PR. The update automatically triggers a rerun of 
   the tests. Hopefully, all the checks will pass then.
* Once your changes are accepted and merged into the repository, they initially show up
   on https://preliminary.istio.io. We publish the changes to https://istio.io
   the next time we do a major release. Typically, we release every 3 months or so.
 
 Thanks for contributing!
 
 _Courtesy of your friendly welcome wagon_.

**Comment by frankbu** [comment]
hyperlinks point to valid location -> hyperlinks point to valid locations

**Pull request closed without merging**
